language: node_js
node_js:
    - '8'
addons:
    chrome: stable
sudo: required
script:
	npm test
	npm run docs:build
before_script:
    - 'sudo chown root /opt/google/chrome/chrome-sandbox'
    - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep_history: true
	local_dir: './docs/.vuepress/dist'
    on:
        branch: master
