language: node_js
node_js:
    - '8'
addons:
    chrome: stable
sudo: required
script:
	npm test
	npm run docs:build
before_script:
    - 'sudo chown root /opt/google/chrome/chrome-sandbox'
    - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
git:
  depth: 10
